theme: jekyll-theme-hacker
title: Welcome to tntimdynomite's homepage!
description: I am trying to keep up with technology and work on some python coding on a platform that hopefully I get more value after
than previous editors I have tried.
